services:
  # PostgreSQL
  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./sql-initializer.sql:/docker-entrypoint-initdb.d/init.sql
      - cash-control-system:/var/lib/postgresql/data
    networks:
      - cash-control-system
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      POSTGRES_USER: ${POSTGRES_DATABASE_USERNAME}
    ports:
      - 6062:5432

  # Interface para Postgres
  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 6063:80
    depends_on:
      - postgres
    networks:
      - cash-control-system

  cash-control-api:
    image: cash-control-api:1.0.0
    build:
      context: ./cash-control
    container_name: cash-control
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - cash-control-system
    environment:
      POSTGRES_DATABASE_USERNAME: ${POSTGRES_DATABASE_USERNAME}
      POSTGRES_DATABASE_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: controlecaixa
      USERNAME_SYSTEM: ${USERNAME_SYSTEM}
      PASSWORD_SYSTEM: ${PASSWORD_SYSTEM}
      JWT_DECODE: ${JWT_DECODE}
    depends_on:
      - postgres

networks:
  cash-control-system:

volumes:
  cash-control-system: